version: "3.9"

services:
#  web:
#    container_name: fastAPI_app
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    env_file:
#      - ./backend/.env
#    command: bash -c "alembic upgrade head && cd /code/app && uvicorn app:app run --host 0.0.0.0 --port 8080 --reload"
#    ports:
#      - "8080:8080"
#    networks:
#      - coffee_shop_network
#    depends_on:
#      - coffee_postgres
#      - coffee_mongo
#    restart: on-failure
#    volumes:
#      - ./:/appS

  coffee_postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ./database.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - "40002:5432"
    networks:
      - coffee_shop_network

  coffee_mongo:
    container_name: coffee_mongo
    image: mongo
    env_file:
      - ./database.env
    volumes:
      - mongo_volume:/data/db
    ports:
      - "40001:27017"
    networks:
      - coffee_shop_network


volumes:
  mongo_volume: {}
  postgres_volume: {}

networks:
  coffee_shop_network:
    driver: "bridge"