"""Initial_2

Revision ID: 405630b92689
Revises: fda9180515bd
Create Date: 2023-05-31 23:53:17.438707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405630b92689'
down_revision = 'fda9180515bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_name_key', 'role', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('role_name_key', 'role', ['name'])
    # ### end Alembic commands ###
