"""unique emails for accounts

Revision ID: 740bda8d57f7
Revises: a4c8d3c48b17
Create Date: 2023-06-09 19:35:12.817062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740bda8d57f7'
down_revision = 'a4c8d3c48b17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'personal_data', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_data', type_='unique')
    # ### end Alembic commands ###
