"""cart

Revision ID: ad9a49c0c1c2
Revises: d45daaab56c7
Create Date: 2023-06-06 19:30:41.159657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9a49c0c1c2'
down_revision = 'd45daaab56c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
