"""add personal_data

Revision ID: d45daaab56c7
Revises: f978be62c447
Create Date: 2023-06-01 01:05:42.335133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45daaab56c7'
down_revision = 'f978be62c447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String().with_variant(sa.String(length=50), 'postgresql'), nullable=False),
    sa.Column('middle_name', sa.String().with_variant(sa.String(length=50), 'postgresql'), nullable=True),
    sa.Column('last_name', sa.String().with_variant(sa.String(length=50), 'postgresql'), nullable=False),
    sa.Column('email', sa.String().with_variant(sa.String(length=50), 'postgresql'), nullable=False),
    sa.Column('phone', sa.String().with_variant(sa.String(length=11), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_data')
    # ### end Alembic commands ###
