"""Initial_2

Revision ID: fda9180515bd
Revises: a07d2c68ab8d
Create Date: 2023-05-31 23:52:02.445197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda9180515bd'
down_revision = 'a07d2c68ab8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
